'use client';

import React, { useState } from 'react';
import { Coins, LineChart } from 'lucide-react';
import { DistributionCharts } from './distributionCharts';
import { BondingCurve } from './bondingCurve';
import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';
import { Toggle } from "@/components/shadcn/toggle";

export function Returns() {
    const [marketType, setMarketType] = useState<'primary' | 'secondary'>('primary');

    const primaryMarketData = [
        { name: 'Partner Fee', value: 2.5, color: '#3b82f6' },
        { name: 'Platform Fee', value: 2.5, color: '#22c55e' }
    ];

    const secondaryMarketData = [
        { name: 'Partner Fee', value: 2, color: '#3b82f6' },
        { name: 'Platform Fee', value: 2, color: '#22c55e' },
        { name: 'Investor Fee', value: 1, color: '#f97316' }
    ];
    return (
        <div className="bg-accent-1 py-24">
            <div className="container">
                <div className="text-center mb-16">
                    <h2 className="text-4xl font-bold">Investment Returns</h2>
                    <h3 className="text-2xl font-semibold mt-4 text-muted-foreground/60">
                        100% of the revenues of our swarms goes to the UBC community and builders
                    </h3>
                    <p className="mt-6 max-w-2xl mx-auto text-muted-foreground">
                        AIs should work for humans, not corporations. Our swarms operate with complete transparency, 
                        ensuring that all revenue is distributed back to the community through token burns and direct rewards.
                    </p>
                </div>

                <div className="space-y-24 px-4">
                    {/* Weekly Revenue System */}
                    <div className="space-y-6">
                        <div className="flex items-center gap-3 mb-8">
                            <div className="h-12 w-12 shrink-0 rounded-xl bg-chart-1/20 flex items-center justify-center">
                                <LineChart className="h-6 w-6 text-chart-1" />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xl font-bold truncate">Weekly Revenue System</h4>
                                <p className="text-muted-foreground truncate">Active revenue processing & distribution</p>
                            </div>
                        </div>
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gradient-to-r from-chart-1 to-chart-2 rounded-lg blur opacity-30 group-hover:opacity-40 transition-opacity" />
                            <div className="relative bg-background/40 backdrop-blur-sm p-6 rounded-lg border border-border/50">
                                <div className="space-y-6">
                                    <div className="flex items-center gap-2 mb-3">
                                        <Coins className="h-5 w-5 shrink-0 text-chart-1" />
                                        <h5 className="font-semibold truncate">Revenue Collection & Distribution</h5>
                                    </div>
                                    <div className="space-y-6">
                                        <div>
                                            <p className="text-muted-foreground mb-4">
                                                Every week, all revenue generated by our swarms is automatically processed through our transparent distribution system:
                                            </p>
                                            <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                                                <li>
                                                    <span className="font-medium text-foreground">Revenue Collection:</span>
                                                    {" "}All swarm revenue is converted to both UBC and partner tokens through market purchases
                                                </li>
                                                <li>
                                                    <span className="font-medium text-foreground">Token Burns:</span>
                                                    {" "}Burned tokens are permanently removed from circulation, increasing scarcity and redistributing value to all token holders
                                                </li>
                                                <li>
                                                    <span className="font-medium text-foreground">Autonomy Levels:</span>
                                                    {" "}Distribution ratios adapt based on each swarm's autonomy level, ensuring fair value distribution between builders and token holders
                                                </li>
                                            </ul>
                                        </div>
                                        <div>
                                            <h6 className="font-semibold mb-4">Distribution & Revenue Calculator</h6>
                                            <DistributionCharts />
                                        </div>
                                        <div>
                                            <h6 className="font-semibold mb-2">Key Benefits</h6>
                                            <ul className="list-disc pl-6 text-sm text-muted-foreground grid grid-cols-2 gap-4">
                                                <li>Transparent revenue distribution</li>
                                                <li>Automatic weekly processing</li>
                                                <li>Fair value sharing model</li>
                                                <li>Sustainable token economics</li>
                                                <li>Community-aligned incentives</li>
                                                <li>Long-term value accrual</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Primary Market */}
                    <div className="space-y-6">
                        <div className="flex items-center gap-3 mb-8">
                            <div className="h-12 w-12 shrink-0 rounded-xl bg-chart-4/20 flex items-center justify-center">
                                <LineChart className="h-6 w-6 text-chart-4" />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xl font-bold truncate">Primary Market</h4>
                                <p className="text-muted-foreground truncate">Bonding Curve</p>
                            </div>
                        </div>
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gradient-to-r from-chart-2 to-chart-3 rounded-lg blur opacity-30 group-hover:opacity-40 transition-opacity" />
                            <div className="relative bg-background/40 backdrop-blur-sm p-6 rounded-lg border border-border/50">
                                <div className="mb-8 space-y-4">
                                    <div className="flex items-center gap-2 mb-3">
                                        <LineChart className="h-5 w-5 shrink-0 text-chart-2" />
                                        <h5 className="font-semibold truncate">Understanding the Bonding Curve</h5>
                                    </div>
                                    <p className="text-muted-foreground">
                                        Our bonding curve rewards early believers while keeping pricing transparent and predictable. 
                                        Simple, fair, and powered by math.
                                    </p>
                                    <div className="grid md:grid-cols-2 gap-6">
                                        <div className="space-y-2">
                                            <h6 className="font-medium text-foreground">Dynamic Pricing</h6>
                                            <p className="text-sm text-muted-foreground">
                                                Share prices increase gradually as more are purchased, rewarding early supporters while maintaining sustainable growth. The curve includes controlled volatility to create natural trading opportunities.
                                            </p>
                                        </div>
                                        <div className="space-y-2">
                                            <h6 className="font-medium text-foreground">Automated Market Making</h6>
                                            <p className="text-sm text-muted-foreground">
                                                Buy and sell prices are determined mathematically, ensuring instant liquidity and eliminating the need for traditional market makers or order books.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <BondingCurve />
                                <div className="mt-12 grid md:grid-cols-2 gap-12">
                                    {/* Left side - Initial Parameters */}
                                    <div className="space-y-4">
                                        <h6 className="text-lg font-semibold">Initial Parameters</h6>
                                        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                                            <li>Starting Price: 1 $COMPUTE</li>
                                            <li>Growth Rate: 35% per 5,000 shares</li>
                                            <li>Maximum Supply: 100,000 shares per swarm</li>
                                            <li>Trading Cycle Length: 5,000 share intervals</li>
                                            <li>Price Volatility: ±30% around base curve</li>
                                        </ul>
                                    </div>

                                    {/* Right side */}
                                    <div className="space-y-4">
                                        <h6 className="text-lg font-semibold">Trading Parameters</h6>
                                        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                                            <li>Instant liquidity via bonding curve</li>
                                            <li>No order books or market makers needed</li>
                                            <li>Predictable price discovery</li>
                                            <li>Natural trading opportunities</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Fee Structure */}
                    <div className="space-y-6">
                        <div className="flex items-center gap-3 mb-8">
                            <div className="h-12 w-12 shrink-0 rounded-xl bg-chart-3/20 flex items-center justify-center">
                                <Coins className="h-6 w-6 text-chart-3" />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xl font-bold truncate">Fee Structure</h4>
                                <p className="text-muted-foreground truncate">
                                    A 5% fee structure that varies between primary and secondary markets, supporting platform operations, 
                                    rewarding ecosystem contributors, and incentivizing active participation
                                </p>
                            </div>
                        </div>
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gradient-to-r from-chart-3 to-chart-4 rounded-lg blur opacity-30 group-hover:opacity-40 transition-opacity" />
                            <div className="relative bg-background/40 backdrop-blur-sm p-6 rounded-lg border border-border/50">
                                {/* Add market toggle */}
                                <div className="flex justify-center mb-8">
                                    <div className="inline-flex items-center p-1 rounded-full bg-black/40 backdrop-blur-sm">
                                        <Toggle
                                            variant="outline"
                                            size="sm"
                                            pressed={marketType === 'primary'}
                                            onPressedChange={() => setMarketType('primary')}
                                            className={`px-6 py-2 rounded-full transition-all duration-200 border-0 ${
                                                marketType === 'primary' 
                                                ? 'bg-white/10 text-white' 
                                                : 'text-white/60 hover:text-white/80'
                                            }`}
                                        >
                                            Primary Market
                                        </Toggle>
                                        <Toggle
                                            variant="outline"
                                            size="sm"
                                            pressed={marketType === 'secondary'}
                                            onPressedChange={() => setMarketType('secondary')}
                                            className={`px-6 py-2 rounded-full transition-all duration-200 border-0 ${
                                                marketType === 'secondary' 
                                                ? 'bg-white/10 text-white' 
                                                : 'text-white/60 hover:text-white/80'
                                            }`}
                                        >
                                            Secondary Market
                                        </Toggle>
                                    </div>
                                </div>

                                <div className="h-64">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <PieChart>
                                            <Pie
                                                data={marketType === 'primary' ? primaryMarketData : secondaryMarketData}
                                                cx="50%"
                                                cy="50%"
                                                innerRadius={60}
                                                outerRadius={90}
                                                paddingAngle={2}
                                                dataKey="value"
                                            >
                                                {(marketType === 'primary' ? primaryMarketData : secondaryMarketData)
                                                    .map((entry, index) => (
                                                        <Cell key={`cell-${index}`} fill={entry.color} />
                                                ))}
                                            </Pie>
                                        </PieChart>
                                    </ResponsiveContainer>
                                </div>

                                <div className="mt-8 grid md:grid-cols-3 gap-8">
                                    {marketType === 'primary' ? (
                                        <>
                                            <div className="space-y-4">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-3 h-3 rounded-full bg-blue-500" />
                                                    <h6 className="font-medium">Partner Fee (2.5%)</h6>
                                                </div>
                                                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                                    <li>Collected in $UBC</li>
                                                    <li>Weekly distribution to partners</li>
                                                    <li>Rewards ecosystem contributors</li>
                                                </ul>
                                            </div>
                                            <div className="space-y-4">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-3 h-3 rounded-full bg-green-500" />
                                                    <h6 className="font-medium">Platform Fee (2.5%)</h6>
                                                </div>
                                                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                                    <li>Funds platform operations</li>
                                                    <li>Supports technical development</li>
                                                    <li>Maintains infrastructure</li>
                                                </ul>
                                            </div>
                                        </>
                                    ) : (
                                        <>
                                            <div className="space-y-4">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-3 h-3 rounded-full bg-blue-500" />
                                                    <h6 className="font-medium">Partner Fee (2%)</h6>
                                                </div>
                                                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                                    <li>Collected directly in $UBC on every trade</li>
                                                    <li>Distributed to partners weekly through automated system</li>
                                                    <li>Rewards ecosystem contributors and growth partners</li>
                                                </ul>
                                            </div>
                                            <div className="space-y-4">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-3 h-3 rounded-full bg-green-500" />
                                                    <h6 className="font-medium">Platform Fee (2%)</h6>
                                                </div>
                                                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                                    <li>Collected in $UBC from each transaction</li>
                                                    <li>Funds essential platform operations</li>
                                                    <li>Supports ongoing technical development</li>
                                                    <li>Maintains infrastructure and security</li>
                                                </ul>
                                            </div>
                                            <div className="space-y-4">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-3 h-3 rounded-full bg-orange-500" />
                                                    <h6 className="font-medium">Investor Redistribution (1%)</h6>
                                                </div>
                                                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                                    <li>Collected in $UBC from every trade</li>
                                                    <li>Claimable by active UBC traders/holders</li>
                                                    <li>30-day window for reward claims</li>
                                                    <li>Encourages regular platform engagement</li>
                                                </ul>
                                            </div>
                                        </>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
