'use client';

import React from 'react';
import { Coins, LineChart } from 'lucide-react';
import { DistributionCharts } from './distributionCharts';
import { BondingCurve } from './bondingCurve';
import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';

export function Returns() {
    return (
        <div className="bg-accent-1 py-24">
            <div className="container">
                <div className="text-center mb-16">
                    <h2 className="text-4xl font-bold">Investment Returns</h2>
                    <h3 className="text-2xl font-semibold mt-4 text-muted-foreground/60">
                        100% of the revenues of our swarms goes to the UBC community and builders
                    </h3>
                    <p className="mt-6 max-w-2xl mx-auto text-muted-foreground">
                        AIs should work for humans, not corporations. Our swarms operate with complete transparency, 
                        ensuring that all revenue is distributed back to the community through token burns and direct rewards.
                    </p>
                </div>

                <div className="space-y-24 px-4">
                    {/* Weekly Revenue System */}
                    <div className="space-y-6">
                        <div className="flex items-center gap-3 mb-8">
                            <div className="h-12 w-12 shrink-0 rounded-xl bg-chart-1/20 flex items-center justify-center">
                                <LineChart className="h-6 w-6 text-chart-1" />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xl font-bold truncate">Weekly Revenue System</h4>
                                <p className="text-muted-foreground truncate">Active revenue processing & distribution</p>
                            </div>
                        </div>
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gradient-to-r from-chart-1 to-chart-2 rounded-lg blur opacity-30 group-hover:opacity-40 transition-opacity" />
                            <div className="relative bg-background/40 backdrop-blur-sm p-6 rounded-lg border border-border/50">
                                <div className="space-y-6">
                                    <div className="flex items-center gap-2 mb-3">
                                        <Coins className="h-5 w-5 shrink-0 text-chart-1" />
                                        <h5 className="font-semibold truncate">Revenue Collection & Distribution</h5>
                                    </div>
                                    <div className="space-y-6">
                                        <div>
                                            <p className="text-muted-foreground mb-4">
                                                Every week, all revenue generated by our swarms is automatically processed through our transparent distribution system:
                                            </p>
                                            <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                                                <li>
                                                    <span className="font-medium text-foreground">Revenue Collection:</span>
                                                    {" "}All swarm revenue is converted to both UBC and partner tokens through market purchases
                                                </li>
                                                <li>
                                                    <span className="font-medium text-foreground">Token Burns:</span>
                                                    {" "}Burned tokens are permanently removed from circulation, increasing scarcity and redistributing value to all token holders
                                                </li>
                                                <li>
                                                    <span className="font-medium text-foreground">Autonomy Levels:</span>
                                                    {" "}Distribution ratios adapt based on each swarm's autonomy level, ensuring fair value distribution between builders and token holders
                                                </li>
                                            </ul>
                                        </div>
                                        <div>
                                            <h6 className="font-semibold mb-4">Distribution & Revenue Calculator</h6>
                                            <DistributionCharts />
                                        </div>
                                        <div>
                                            <h6 className="font-semibold mb-2">Key Benefits</h6>
                                            <ul className="list-disc pl-6 text-sm text-muted-foreground grid grid-cols-2 gap-4">
                                                <li>Transparent revenue distribution</li>
                                                <li>Automatic weekly processing</li>
                                                <li>Fair value sharing model</li>
                                                <li>Sustainable token economics</li>
                                                <li>Community-aligned incentives</li>
                                                <li>Long-term value accrual</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Primary Market */}
                    <div className="space-y-6">
                        <div className="flex items-center gap-3 mb-8">
                            <div className="h-12 w-12 shrink-0 rounded-xl bg-chart-4/20 flex items-center justify-center">
                                <LineChart className="h-6 w-6 text-chart-4" />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xl font-bold truncate">Primary Market</h4>
                                <p className="text-muted-foreground truncate">Bonding Curve</p>
                            </div>
                        </div>
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gradient-to-r from-chart-2 to-chart-3 rounded-lg blur opacity-30 group-hover:opacity-40 transition-opacity" />
                            <div className="relative bg-background/40 backdrop-blur-sm p-6 rounded-lg border border-border/50">
                                <div className="mb-8 space-y-4">
                                    <div className="flex items-center gap-2 mb-3">
                                        <LineChart className="h-5 w-5 shrink-0 text-chart-2" />
                                        <h5 className="font-semibold truncate">Understanding the Bonding Curve</h5>
                                    </div>
                                    <p className="text-muted-foreground">
                                        Our bonding curve rewards early believers while keeping pricing transparent and predictable. 
                                        Simple, fair, and powered by math.
                                    </p>
                                    <div className="grid md:grid-cols-2 gap-6">
                                        <div className="space-y-2">
                                            <h6 className="font-medium text-foreground">Dynamic Pricing</h6>
                                            <p className="text-sm text-muted-foreground">
                                                Share prices increase gradually as more are purchased, rewarding early supporters while maintaining sustainable growth. The curve includes controlled volatility to create natural trading opportunities.
                                            </p>
                                        </div>
                                        <div className="space-y-2">
                                            <h6 className="font-medium text-foreground">Automated Market Making</h6>
                                            <p className="text-sm text-muted-foreground">
                                                Buy and sell prices are determined mathematically, ensuring instant liquidity and eliminating the need for traditional market makers or order books.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <BondingCurve />
                                <div className="mt-12 grid md:grid-cols-2 gap-12">
                                    {/* Left side - Initial Parameters */}
                                    <div className="space-y-4">
                                        <h6 className="text-lg font-semibold">Initial Parameters</h6>
                                        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                                            <li>Starting Price: 1 $COMPUTE</li>
                                            <li>Growth Rate: 35% per 5,000 shares</li>
                                            <li>Maximum Supply: 100,000 shares per swarm</li>
                                            <li>Trading Cycle Length: 5,000 share intervals</li>
                                            <li>Price Volatility: ±30% around base curve</li>
                                        </ul>
                                    </div>

                                    {/* Right side */}
                                    <div className="space-y-4">
                                        <h6 className="text-lg font-semibold">Trading Parameters</h6>
                                        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                                            <li>Instant liquidity via bonding curve</li>
                                            <li>No order books or market makers needed</li>
                                            <li>Predictable price discovery</li>
                                            <li>Natural trading opportunities</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Fee Structure Section */}
                    <div className="space-y-6">
                        <div className="flex items-center gap-3 mb-8">
                            <div className="h-12 w-12 shrink-0 rounded-xl bg-chart-3/20 flex items-center justify-center">
                                <Coins className="h-6 w-6 text-chart-3" />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xl font-bold truncate">Fee Structure</h4>
                                <p className="text-muted-foreground truncate">
                                    Simple 5% platform fee in $UBC
                                </p>
                            </div>
                        </div>
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gradient-to-r from-chart-3 to-chart-4 rounded-lg blur opacity-30 group-hover:opacity-40 transition-opacity" />
                            <div className="relative bg-background/40 backdrop-blur-sm p-6 rounded-lg border border-border/50">

                                {/* Fee Mechanics */}
                                <div className="space-y-4">
                                    <h6 className="text-lg font-semibold mb-4">Fee Mechanics</h6>
                                    <p className="text-muted-foreground">
                                        A straightforward 5% platform fee is charged in $UBC tokens for all transactions. 
                                        This fee helps maintain platform infrastructure and support ongoing development.
                                    </p>
                                    
                                    <div className="bg-black/20 p-4 rounded-lg">
                                        <p className="text-sm text-muted-foreground">
                                            Example: When investing 1000 $COMPUTE:
                                            <br />
                                            Fee = 50 $UBC (5% of 1000)
                                        </p>
                                    </div>

                                    <div className="bg-yellow-500/10 border border-yellow-500/20 p-4 rounded-lg">
                                        <p className="text-yellow-500 text-sm">
                                            <strong>Important:</strong> Investors must have sufficient $UBC in their 
                                            wallet to cover fees when investing. This mechanism provides utility to 
                                            the $UBC token while supporting platform operations.
                                        </p>
                                    </div>
                                </div>

                                {/* Key Points */}
                                <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
                                    <div>
                                        <h6 className="font-medium text-white/80 mb-2">Transparency</h6>
                                        <p className="text-sm text-white/60">
                                            All fees are handled through smart contracts with complete on-chain transparency.
                                        </p>
                                    </div>
                                    <div>
                                        <h6 className="font-medium text-white/80 mb-2">Automation</h6>
                                        <p className="text-sm text-white/60">
                                            Fee collection process is fully automated, ensuring consistent execution.
                                        </p>
                                    </div>
                                    <div>
                                        <h6 className="font-medium text-white/80 mb-2">Simplicity</h6>
                                        <p className="text-sm text-white/60">
                                            One simple fee covers all platform operations and maintenance.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    );
}
